### ISSUE TITLE
[BUG] Button title broken and mod not working as expected(?)

### ISSUE THREAD

**Issue by thatAkiraFox** [ModManagerMC/ModManager#145]
**Describe the bug**
The first bug is a simple one, aka the title which appears on cursor hover is broken.

The second issue is a bit weird, as my mod interface appears completely different from the screenshots. Am I doing something wrong here?
Also, even tho apparently Mod Manager is able to search and find mod updates, it doesn't show anything in the mod screen.

**To Reproduce**
For the first issue you just hover on the Mod Manager button in Mod Menu

For the second issue you need to actually access Mod Manager

**Expected behavior**
In the first case, a normal-rendered tooltip is expected

For the second issue, an "usual" interface is expected and updatable mods are showed

**Screenshots**
![Screenshot from 2022-04-22 00-49-46](https://user-images.githubusercontent.com/49398464/164564381-90a8d958-9287-4141-be09-27d6c25bb91a.png)
![Screenshot from 2022-04-22 00-49-51](https://user-images.githubusercontent.com/49398464/164564395-86aa459f-92d1-49c8-b060-0bc3eeafdb84.png)

**Please complete the following information:**
 - OS: EndeavourOS (Arch Linux)
 - Minecraft version 1.18.2
 - Version 1.2.3

**Logs**
Latest log:
[latest.log](https://github.com/ModManagerMC/ModManager/files/8535563/latest.log)

Crash-report (if any):

**Additional context**
Don't know if this information can be useful but I'm using PolyMC 1.2.1 Flatpak build.

**Comment by joseph-20** [comment]
Uhm, no help or info of any sort on this?

**Comment by DeathsGun** [comment]
I need to look into this, but don't have much time at the moment

**Comment by joseph-20** [comment]
Got it, no worries, thanks for answering me

**Comment by joseph-20** [comment]
FIXED THIS!

I'm so sorry, it was due to the Modget mod being installed, since it too has the same mod updates button placed exactly where Mod Manager places its button.

Removing Modget fixes everything, sorry for bothering you.

**Comment by DeathsGun** [comment]
Wait modget places a button in UI? I tought modget is command only

**Comment by DeathsGun** [comment]
Wow they even use my texture for the install button

**Comment by joseph-20** [comment]
Yikes.
