### ISSUE TITLE
[BUG] ModManager conflicts with Ok Zoomer

### ISSUE THREAD

**Issue by Diridibindy** [ModManagerMC/ModManager#153]
"ModManager" conflicts with "Ok Zoomer"

**To Reproduce**
Use "ModManager" its dependencies together with "Ok Zoomer"

**Expected behavior**
The game launches

**Please complete the following information:**
 - OS: Arch Linux
 - Minecraft version: 1.18.2
 - Version: Latest

**Logs**

[log.txt](https://github.com/ModManagerMC/ModManager/files/8854137/log.txt)

Crash-report:

[log.txt](https://github.com/ModManagerMC/ModManager/files/8854151/log.txt)

**Comment by Diridibindy** [comment]
Nvm its due to some oddities in the Ok Zoomer mod since they switched to quilt, loading the game with quilt loader removes this crash

**Comment by DeathsGun** [comment]
Yeah and ModManager using preLaunch which is a little buggy with stacktraces
