### ISSUE TITLE
Ability to Disable and Enable mods at any time

### ISSUE THREAD

**Issue by Drigonis** [ModManagerMC/ModManager#156]
**Is your feature request related to a problem? Please describe.**
I'm making a modpack and I want to be able to play on servers like normal, but play modded Minecraft in singleplayer. Essentially, I want to disable specific server-side mods when I go multiplayer but re-enable them when I go to singleplayer, but instead I have to reopen the game with new mods downloaded, or make another modpack entirely.

**Describe the solution you'd like**
I would appreciate if you could add the ability to enable / disable mods (maybe by moving them into another folder when disabled?), and mark specific worlds or folders as modded and select which mods you want enabled and disabled when entering. This would completely reimagine the Minecraft experience because you could play modded in singleplayer without sacrificing access to vanilla servers, and also be able to join modded servers at the same time.

**Describe alternatives you've considered**
Alternatively, it could just be disabled or enabled manually without the extra stuff like mod sets for each world or server if doing such a thing is too difficult.

One thing I'd like to mention is, would this work? When you enable a mod, would it be possible for it to work immediately without having to restart the game? I would really appreciate it if you could somehow make this work. Thank you!

**Comment by DeathsGun** [comment]
The mod set switching part get's discussed in #140. The part with loading/unloading mods without restart isn't supported by fabric.
