### ISSUE TITLE
[BUG] Why is this archived on Modrinth but not GitHub?

### ISSUE THREAD

**Issue by danielzgtg** [ModManagerMC/ModManager#158]
**Describe the bug**

On Modrinth I see a red box with "Mod Manager has been archived by the project author. Mod Manager will not receive any further updates unless the author decides to unarchive the project." However, I see this GitHub project is not archived and there is no explanation in the README. I am on 1.18.2 and the mod works fine for me. Is this project archived or not?

**To Reproduce**
1. Go to https://modrinth.com/mod/modmanager
2. See a red archived box
3. Go to https://github.com/ModManagerMC/ModManager
4. See no yellow archived banner

**Expected behavior**
Either both should say archived or neither says archived. If this is really archived, which I hope not, there should be an explanation in the README

**Screenshots**
![image](https://user-images.githubusercontent.com/25646384/210081899-1d155a5f-0f8d-4db2-8b17-13356c65cdd0.png)

**Please complete the following information:**
 - OS: [e.g. Windows 10] (Firefox, this is not an ingame problem)
 - Minecraft version [e.g. 1.17.1, 21w22a] 1.18.2
 - Version [e.g. 1.0.0-alpha] 1.2.3+1.18.2

**Logs**
This is not an ingame problem.

**Comment by DeathsGun** [comment]
Will be archived
